### PR TITLE
Feat: don't change text if nothing to do

### PR DESCRIPTION
**Pull request by backdround**
If there was an accidental hitting on the wrong button and the code hasn't changed, the vim considers it a changed buffer (the `modified` option is set). It's a little annoying, so the pr is here.

The solution is to check for changes before setting the text.

I'm not sure:
- should I use `pcall` to call `nvim_buf_get_text`? (I don't why there is `pcall(vim.api.nvim_buf_set_tex...` on the next line
- should I `notify.info` that nothing has changed?

### CODE REVIEW

**Comment by Wansmer** [comment]
This PR affects the functionality separately for `split` and separately for `join`, but not for `toggle` when the text is changed anyway. 
So it doesn't make sense to do the check after the node is processed - better to do the check based on the passed mode and compare it with the auto-detected mode ([e.g. here](https://github.com/Wansmer/treesj/blob/dd4801166a44df4a3b179d5a5a71b05cf6129d71/lua/treesj/format.lua#L90)). At this point, you can notify the user that the current node is already splitted/joined.

(By the way, I originally wanted to add this functionality, but gave up. Unfortunately, I can't remember the reason why I didn't add it.)

**Comment by backdround** [comment]
I didn't catch the thing about "it doesn't affect toggle". Should it affect toggle too? If it should then I don't understand the case.

Also I'm not sure that the check should be before the `fallback` test. What do you think?

**Comment by Wansmer** [comment]
> I didn't catch the thing about "it doesn't affect toggle". Should it affect toggle too? If it should then I don't understand the case.

No, you don't. The point was that you don't need to do an unnecessary comparison between the original and the processed text, because in the case of `toggle` it is always irrelevant. It is cheaper to do it before any processing.

> Also I'm not sure that the check should be before the fallback test. What do you think?

Yes, you are absolutely right, it is more correct to check for `fallback` first. That is, just remove this check from the loop because its logic will not change.

**Comment by backdround** [comment]
It should be ok now

**Comment by Wansmer** [comment]
Thanks for PR!

**Comment by backdround** [comment]
@Wansmer Thank for the plugin!

**Pull request merged**
