### PR TITLE
Support `php_only` subset

### PR DESCRIPTION
**Pull request by przepompownia**

### CODE REVIEW

**Comment by Wansmer** [comment]
Thanks for the PR!
Please add `php_only` to the[ languages section](https://github.com/Wansmer/treesj?tab=readme-ov-file#languages) of README.md and create test files [like for regular ](https://github.com/Wansmer/treesj/blob/main/tests/sample/index.php)`php`. 

More about tests [here](https://github.com/Wansmer/treesj/blob/main/tests/README.md).

**Comment by przepompownia** [comment]
Looks like copy-paste (because of the same parser). What do you propose to avoid duplication?

> Thanks for the PR! Please add `php_only` to the[ languages section](https://github.com/Wansmer/treesj?tab=readme-ov-file#languages) of README.md and create test files [like for regular ](https://github.com/Wansmer/treesj/blob/main/tests/sample/index.php)`php`.

**Comment by Wansmer** [comment]
> Looks like copy-paste (because of the same parser). What do you propose to avoid duplication?

If it's just a copy and paste, you don't need to. 
Does `php_only` and `php` have the same file extension?
If so, let me know and I'll merge the PR.

**Comment by przepompownia** [comment]
If I understand correctly, `php_only` does not include injections for HTML - look at the queries in nvim-treesitter.

**Comment by przepompownia** [comment]
Yes, both are for `php` but although I need to call
```lua
vim.treesitter.language.register('php_only', {'php'})
```
from my configs.

**Comment by przepompownia** [comment]
Thanks!

**Pull request merged**
