### PR TITLE
Basic elixir support

### PR DESCRIPTION
**Pull request by edgurgel**
Thanks for the great project! 

This PR adds basic support to Elixir. I've implemented just the most basic setup to get started but hopefully we can improve it later.

* lists
* tuples
* arguments

I've tried my best to include support for maps but I couldn't find a way to make this work :disappointed: 

I think the main issue is that `map` holds a `map_content` which then holds the children key-values.  

```
    right: (map ; [16, 6] - [20, 1]
      (map_content ; [17, 2] - [19, 13]
        (binary_operator ; [17, 2] - [17, 15]
          left: (atom) ; [17, 2] - [17, 6]
          right: (string ; [17, 10] - [17, 15]
            (quoted_content))) ; [17, 11] - [17, 14]
        (binary_operator ; [18, 2] - [18, 15]
          left: (atom) ; [18, 2] - [18, 6]
          right: (string ; [18, 10] - [18, 15]
            (quoted_content))) ; [18, 11] - [18, 14]
        (binary_operator ; [19, 2] - [19, 13]
          left: (list ; [19, 2] - [19, 8]
            (integer) ; [19, 3] - [19, 4]
            (integer)) ; [19, 6] - [19, 7]
          right: (integer))))) ; [19, 12] - [19, 13]
```

### CODE REVIEW

**Comment by Wansmer** [comment]
Hi! Thanks for the PR.

Here is an example of the customization for `map` and `map_content`. Please add this to your PR.

```lua
  map = {
    target_nodes = { 'map_content' },
  },
  map_content = lang_utils.set_preset_for_list({
    both = {
      non_bracket_node = true,
    },
    split = {
      last_separator = false,
    },
    join = {
      space_in_brackets = false,
    },
  })
```


Also, you are not using `utils` in your code, so no need to require it.

**Comment by edgurgel** [comment]
Nice! That worked! I didn't think of using `non_bracket_node` :bulb: . Thanks! :tada:

**Comment by edgurgel** [comment]
Please don't merge it just yet! I've found an edge case on the map handling! I will push the failing test later today!

**Comment by edgurgel** [comment]
Ok I've pushed the issue I found with map including `map_content` AND `keywords` :cry: 

```treesitter
    right: (map ; [64, 6] - [68, 1]
      (map_content ; [65, 2] - [67, 12]
        (binary_operator ; [65, 2] - [65, 18]
          left: (string ; [65, 2] - [65, 7]
            (quoted_content)) ; [65, 3] - [65, 6]
          right: (string ; [65, 11] - [65, 18]
            (quoted_content))) ; [65, 12] - [65, 17]
        (keywords ; [66, 2] - [67, 12]
          (pair ; [66, 2] - [66, 12]
            key: (keyword) ; [66, 2] - [66, 7]
            value: (string ; [66, 7] - [66, 12]
              (quoted_content))) ; [66, 8] - [66, 11]
          (pair ; [67, 2] - [67, 12]
            key: (keyword) ; [67, 2] - [67, 7]
            value: (string ; [67, 7] - [67, 12]
              (quoted_content)))))))) ; [67, 8] - [67, 11]
```

Here `"key" => "value"` is inside `map_content` and the rest is inside `keywords`

```elixir
map = %{
  "key" => "value",
  foo: "bar",
  baz: "bar"
}
```

This is where is failing atm:

```
Fail	||	TreeSJ SPLIT: lang "elixir", node "map" with "keywords" and "map_content", preset default	
            ./tests/utils.lua:21: Expected objects to be the same.
            Passed in:
            (table: 0x74be51d62070) {
              [1] = 'map = %{'
              [2] = '  "key" => "value",'
             *[3] = '  foo: "bar", baz: "bar"'
              [4] = '}'
              [5] = '' }
            Expected:
            (table: 0x74be51c75130) {
              [1] = 'map = %{'
              [2] = '  "key" => "value",'
             *[3] = '  foo: "bar",'
              [4] = '  baz: "bar"'
              [5] = '}' }
```

Any suggestions? :thinking:

**Comment by Wansmer** [comment]
Technically, this is correct behavior because `keywords` is a separate wrapped node  in this case.

You can use the `format_tree` function to handle this case, e.g:

```lua
  map_content = lang_utils.set_preset_for_list({
    both = {
      non_bracket_node = true,
    },
    split = {
      last_separator = false,
      format_tree = function(tsj)
        if tsj:has_children({ 'keywords' }) then
          tsj:update_preset({ recursive = true }, 'split')
          local keywords = tsj:child('keywords')
          keywords:update_preset({ inner_indent = 'normal' }, 'split')
        end
      end,
    },
    join = {
      space_in_brackets = false,
    },
  }),
```

(I am not sure if this code covers all cases with `keywords` inside `map_content`)

I also noticed that the code in `langs/elixir.lua` is not formatted according to `stylua.toml`. Please use a formatter before the final PR

**Comment by edgurgel** [comment]
Thanks for the suggestion!

Ok I think I fixed all the weird edge cases I found with keywords. I ended up adding something I think it's a bit of a hack inside `keywords` I'm using `format_resulted_lines` to fix something I couldn't really understand why it happens. 

Without that I get this failing error where the keyword pair is merged: `map:%{` instead of `map: %{`. It doesn't happen on the non-keyword part (`"map" => %{"key`) :thinking: 

```
Fail	||	TreeSJ SPLIT: lang "elixir", node "map" nested "keywords" and "maps", preset default	
            ./tests/utils.lua:21: Expected objects to be the same.
            Passed in:
            (table: 0x7e964657f0b0) {
              [1] = 'map = %{'
              [2] = '  "map" => %{"key" => "value"},'
              [3] = '  foo: "bar",'
             *[4] = '  map:%{"key" => "value"},'
              [5] = '  baz: "bar"'
              [6] = '}' }
            Expected:
            (table: 0x7e9646616488) {
              [1] = 'map = %{'
              [2] = '  "map" => %{"key" => "value"},'
              [3] = '  foo: "bar",'
             *[4] = '  map: %{"key" => "value"},'
              [5] = '  baz: "bar"'
              [6] = '}' }
```

I also ran stylua. Hopefully it's all formatted properly now!

**Comment by Wansmer** [comment]
> Without that I get this failing error where the keyword pair is merged: map:%{ instead of map: %{. It doesn't happen on the non-keyword part ("map" => %{"key) 🤔

I have tested this case: It looks like the problem with the space in `keywords` is related to the parser quirks for elixir.

For now, using `format_resulted_lines` is the best solution, but I will investigate this problem in more detail in the future. 

If you don't plan to add anything else, I will merge this PR.

**Comment by edgurgel** [comment]
Thanks for checking it out! Yeah the elixir treesitter has some oddities!

I've just pushed a final change to use `format_tree` with a more targeted approach I guess. It seems less hacky then using `formatted_resulted_lines`. 

If you are happy with the outcome I'm done with this PR! 

Hoping to improve the elixir support in the near future for anonymous functions and other bits and pieces but I might need to open a couple of issues on the  elixir treesitter repo

**Comment by Wansmer** [comment]
> If you are happy with the outcome I'm done with this PR!

Everything is great, thanks for your contribution!

**Comment by edgurgel** [comment]
Thank you this great project! Excellent framework you built here 🏆

**Pull request merged**
